# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\git\ece57000\UserInterface\uiRecipeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecipeDialog(object):
    def setupUi(self, RecipeDialog):
        RecipeDialog.setObjectName("RecipeDialog")
        RecipeDialog.resize(581, 411)
        self.verticalLayoutWidget = QtWidgets.QWidget(RecipeDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.recipeNameLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recipeNameLbl.setFont(font)
        self.recipeNameLbl.setObjectName("recipeNameLbl")
        self.horizontalLayout_2.addWidget(self.recipeNameLbl)
        self.recipeName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recipeName.setFont(font)
        self.recipeName.setObjectName("recipeName")
        self.horizontalLayout_2.addWidget(self.recipeName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.recipeTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.recipeTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recipeTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.recipeTable.setRowCount(11)
        self.recipeTable.setColumnCount(3)
        self.recipeTable.setObjectName("recipeTable")
        item = QtWidgets.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recipeTable.setHorizontalHeaderItem(2, item)
        self.recipeTable.horizontalHeader().setCascadingSectionResizes(False)
        self.recipeTable.horizontalHeader().setDefaultSectionSize(50)
        self.recipeTable.horizontalHeader().setMinimumSectionSize(25)
        self.recipeTable.horizontalHeader().setStretchLastSection(True)
        self.recipeTable.verticalHeader().setVisible(False)
        self.recipeTable.verticalHeader().setDefaultSectionSize(25)
        self.recipeTable.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout.addWidget(self.recipeTable)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RecipeDialog)
        self.buttonBox.accepted.connect(RecipeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RecipeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RecipeDialog)

    def retranslateUi(self, RecipeDialog):
        _translate = QtCore.QCoreApplication.translate
        RecipeDialog.setWindowTitle(_translate("RecipeDialog", "Recipe Editor"))
        self.recipeNameLbl.setText(_translate("RecipeDialog", "Recipe Name:"))
        item = self.recipeTable.horizontalHeaderItem(0)
        item.setText(_translate("RecipeDialog", "Qty"))
        item = self.recipeTable.horizontalHeaderItem(1)
        item.setText(_translate("RecipeDialog", "Unit"))
        item = self.recipeTable.horizontalHeaderItem(2)
        item.setText(_translate("RecipeDialog", "Ingredient"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecipeDialog = QtWidgets.QDialog()
    ui = Ui_RecipeDialog()
    ui.setupUi(RecipeDialog)
    RecipeDialog.show()
    sys.exit(app.exec_())
