# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\git\ece57000\UserInterface\.\uiTargetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_macroTargets(object):
    def setupUi(self, macroTargets):
        macroTargets.setObjectName("macroTargets")
        macroTargets.resize(444, 173)
        self.buttonBox = QtWidgets.QDialogButtonBox(macroTargets)
        self.buttonBox.setGeometry(QtCore.QRect(80, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(macroTargets)
        self.label.setGeometry(QtCore.QRect(20, 20, 261, 16))
        self.label.setObjectName("label")
        self.lblCarbs = QtWidgets.QLabel(macroTargets)
        self.lblCarbs.setGeometry(QtCore.QRect(50, 40, 141, 22))
        self.lblCarbs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCarbs.setObjectName("lblCarbs")
        self.lblProtein = QtWidgets.QLabel(macroTargets)
        self.lblProtein.setGeometry(QtCore.QRect(50, 60, 141, 22))
        self.lblProtein.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProtein.setObjectName("lblProtein")
        self.lblFat = QtWidgets.QLabel(macroTargets)
        self.lblFat.setGeometry(QtCore.QRect(50, 80, 141, 22))
        self.lblFat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFat.setObjectName("lblFat")
        self.lblPrompt2 = QtWidgets.QLabel(macroTargets)
        self.lblPrompt2.setGeometry(QtCore.QRect(290, 20, 131, 16))
        self.lblPrompt2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPrompt2.setObjectName("lblPrompt2")
        self.dblCarbs = QtWidgets.QDoubleSpinBox(macroTargets)
        self.dblCarbs.setGeometry(QtCore.QRect(200, 40, 40, 22))
        self.dblCarbs.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dblCarbs.setDecimals(0)
        self.dblCarbs.setMaximum(100.0)
        self.dblCarbs.setObjectName("dblCarbs")
        self.dblProtein = QtWidgets.QDoubleSpinBox(macroTargets)
        self.dblProtein.setGeometry(QtCore.QRect(200, 60, 40, 22))
        self.dblProtein.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dblProtein.setDecimals(0)
        self.dblProtein.setMaximum(100.0)
        self.dblProtein.setObjectName("dblProtein")
        self.dblFat = QtWidgets.QDoubleSpinBox(macroTargets)
        self.dblFat.setGeometry(QtCore.QRect(200, 80, 40, 22))
        self.dblFat.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dblFat.setDecimals(0)
        self.dblFat.setMaximum(100.0)
        self.dblFat.setObjectName("dblFat")
        self.dblSatFat = QtWidgets.QDoubleSpinBox(macroTargets)
        self.dblSatFat.setGeometry(QtCore.QRect(380, 60, 40, 22))
        self.dblSatFat.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dblSatFat.setDecimals(0)
        self.dblSatFat.setMaximum(100.0)
        self.dblSatFat.setSingleStep(0.1)
        self.dblSatFat.setObjectName("dblSatFat")
        self.dblSugar = QtWidgets.QDoubleSpinBox(macroTargets)
        self.dblSugar.setGeometry(QtCore.QRect(380, 40, 40, 22))
        self.dblSugar.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dblSugar.setDecimals(0)
        self.dblSugar.setMaximum(100.0)
        self.dblSugar.setObjectName("dblSugar")
        self.lblSugar = QtWidgets.QLabel(macroTargets)
        self.lblSugar.setGeometry(QtCore.QRect(300, 40, 71, 22))
        self.lblSugar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSugar.setObjectName("lblSugar")
        self.lblSatFat = QtWidgets.QLabel(macroTargets)
        self.lblSatFat.setGeometry(QtCore.QRect(300, 60, 71, 22))
        self.lblSatFat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSatFat.setObjectName("lblSatFat")
        self.lblWarning = QtWidgets.QLabel(macroTargets)
        self.lblWarning.setGeometry(QtCore.QRect(80, 110, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblWarning.setFont(font)
        self.lblWarning.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblWarning.setObjectName("lblWarning")

        self.retranslateUi(macroTargets)
        self.buttonBox.accepted.connect(macroTargets.accept) # type: ignore
        self.buttonBox.rejected.connect(macroTargets.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(macroTargets)

    def retranslateUi(self, macroTargets):
        _translate = QtCore.QCoreApplication.translate
        macroTargets.setWindowTitle(_translate("macroTargets", "Macronutrient Targets"))
        self.label.setText(_translate("macroTargets", "Enter macronutrient composition percentages:"))
        self.lblCarbs.setText(_translate("macroTargets", "Net Carbohydrates"))
        self.lblProtein.setText(_translate("macroTargets", "Protein"))
        self.lblFat.setText(_translate("macroTargets", "Total Fat"))
        self.lblPrompt2.setText(_translate("macroTargets", "Adverse substance limits:"))
        self.dblCarbs.setSuffix(_translate("macroTargets", "%"))
        self.dblProtein.setSuffix(_translate("macroTargets", "%"))
        self.dblFat.setSuffix(_translate("macroTargets", "%"))
        self.dblSatFat.setSuffix(_translate("macroTargets", "g"))
        self.dblSugar.setSuffix(_translate("macroTargets", "g"))
        self.lblSugar.setText(_translate("macroTargets", "Added Sugar"))
        self.lblSatFat.setText(_translate("macroTargets", "Saturated Fat"))
        self.lblWarning.setText(_translate("macroTargets", "Percentages must equal 100%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    macroTargets = QtWidgets.QDialog()
    ui = Ui_macroTargets()
    ui.setupUi(macroTargets)
    macroTargets.show()
    sys.exit(app.exec_())
